### ISSUE TITLE
Feature request/ question

### ISSUE THREAD

**Issue by seanhakbb** [koktaildotcom/homey-mi-flora#104]
So I used the flowercare app to setup my devices and download latest firmware, and then managed to get it working with this app in homey.

My problem is however, the name won’t follow through and I can’t seem to find a way to identify them. Is there a way to see the ID in the flowercare app? Or trigger LED light from your app?

currently have 6 mi sensors, but the notifications don’t help me at all since they are named “mi flora sensor 1” etc

I have a really long interval to preserve battery, so the sensor values can’t match the app (ie, try finding sensor in flowercare app that matches notification)

sorry for submitting this nontechnical issue here but homey one thread support discussion is a mess and I would likely miss an answer there anyways…
Thanks for your great work!

**Comment by koktaildotcom** [comment]
I've added an identification meganism once, but that wasn't stable enough. Can try if that is solved now with the new firmware. Or I can try to determine the range based on the rssi output.
