### ISSUE TITLE
No sensor updates anymore after 7.1.6 version of homey

### ISSUE THREAD

**Issue by dbuekenh** [koktaildotcom/homey-mi-flora#110]
Dear,

It seems that after the homey update the sensors are not updated anymore.
Before that everything was working fine.

![image2](https://user-images.githubusercontent.com/47578509/143316450-8226231f-98ba-4ad1-a823-fc22b88c197d.png)
![image0](https://user-images.githubusercontent.com/47578509/143316445-41fcb960-3897-40c2-8da6-59f95de8767f.png)
![image1](https://user-images.githubusercontent.com/47578509/143316448-b0e991a0-8180-4bb3-9c6a-e9be2dbcdfeb.png)

Rgds Dirk

**Comment by koktaildotcom** [comment]
I cannot reproduce your issue. Can you try to (PTP) pull the power cable of your homey and reboot the device? And after that send a diagnostic report to the developer. I'll have a look what I can find.

**Comment by dbuekenh** [comment]
Dear, homey upgraded to 7.2.0 an now both sensors are again working.
But meanwhile i pulled out the cable to, because in the morning all devices showed a red esclamination. 
Now everything is working again.

**Comment by koktaildotcom** [comment]
Good to hear your issue is resolved.
