### ISSUE TITLE
[enhancement] add validation on device setting (min/max).

### ISSUE THREAD

**Issue by cbho** [koktaildotcom/homey-mi-flora#12]
Suggestion:
When adding a minimum value, the max value is automatically changed to being at least 1 higher than that.
Would prevent a situation with "impossible" values (having a maximum limit that is lower than the lower limit).
Not a big deal, just an idea ;-)

**Comment by koktaildotcom** [comment]
I changed the issue title. Thanks for adding the issue.

**Comment by koktaildotcom** [comment]
resolved in https://github.com/koktaildotcom/homey-mi-flora/releases/tag/2.0.0
