### ISSUE TITLE
Swedish translation in the sensor_threshold_min_exceeds.json

### ISSUE THREAD

**Issue by dansav** [koktaildotcom/homey-mi-flora#137]
The Swedish translation for `Sensor value is below the configured threshold` should be:

 `Sensorns värde är under det inställda tröskelvärdet`

It would be great if you could update this in your next release. Thanks!

**Comment by koktaildotcom** [comment]
Thanks for your contribution. Are there any other translation errors?

**Comment by dansav** [comment]
No, the other strings look fine to me.

**Comment by koktaildotcom** [comment]
Will be available on: 4.0.8
