### ISSUE TITLE
Mobile interface not shown in new (beta) app

### ISSUE THREAD

**Issue by TedTolboom** [koktaildotcom/homey-mi-flora#3]
Hi @koktaildotcom,

Great app, thanks for the effort.

I noticed that the mobile interface is showing correctly on the old web interface:
<img width="341" alt="schermafbeelding 2018-04-10 om 08 00 08" src="https://user-images.githubusercontent.com/17163431/38538731-65f718ce-3c95-11e8-80d7-c7df559593d7.png">

But on the new (beta) app, the interface only shows a blank screen (adding a screenshot doesn't make sense).
I tried to optimize the icons (with illustrator) to check if that resolves this issue (see PR#2), but that is not the case...

I'll see if I can look into it this evening.

PS. I would propose to setup a paypalme account and replace your current contribution link to that one; saves Paypal fees... ;-P

**Comment by TedTolboom** [comment]
Thinking out loud... 

this could be caused by the custom capabilities being defined as setable and at the same time being added to a sensor component of the mobile interface... Currently not in reach of my Homey, will try this evening.

But for sure, it is not needed to have these custom capabilities as setable, since only the device (and not the user) will update the capability values.

**Comment by TedTolboom** [comment]
Just updated the PR to change setable to false and remove the obsolete min, max and step size (only needed for setting). Did not test it myself yet.

**Comment by koktaildotcom** [comment]
Thanks @TedTolboom! Your PR resolved the issue. The above assumption of the `custom capabilities being defined as setable` didn't cause it because i revert that code (they must be settable in the sync process.)

I think it was the missing `battery_capability` with the `battery` sensor.
