### ISSUE TITLE
RoPot values not available in mobile app (iOS v.2) (but is in v.1)

### ISSUE THREAD

**Issue by cbho** [koktaildotcom/homey-mi-flora#33]
App v. 2.0.3 (and 2.0.6)
Readings from my RoPots are available when using the desktop app or browser, but not when using the mobile app (v.2 for iOS, 1.1.107). However, in the original Homey app (for iOS), readings are shown...

**Comment by koktaildotcom** [comment]
Do you know if the readings where available in the versions 2.0.0 or 2.0.1?

**Comment by cbho** [comment]
I cannot say for certain, but as far as I remember, they were missing in 2.0.0 and 2.0.1 as well

**Comment by koktaildotcom** [comment]
Cannot validate the issue due to not having iOS. Think we need to wait for final release of the app for verifying the issue again.
