### ISSUE TITLE
Too many settings available for RoPot

### ISSUE THREAD

**Issue by cbho** [koktaildotcom/homey-mi-flora#34]
Under settings for RoPots, it is possible to add limits for "luminance".
However, RoPots unfortunately haven't got that capability.
Suggest deleting the setting as I guess it could be confusing in some cases.

**Comment by koktaildotcom** [comment]
I'll make the settings device capability dependent.

**Comment by koktaildotcom** [comment]
Will be resolved in https://github.com/koktaildotcom/homey-mi-flora/releases/tag/2.0.7

**Comment by cbho** [comment]
Issue resolved - confirmed as requested ;-)

**Comment by koktaildotcom** [comment]
Thanks for your feedback! Happy to help
