### ISSUE TITLE
lost connection

### ISSUE THREAD

**Issue by LyoshaDovolen** [koktaildotcom/homey-mi-flora#35]
distance of 3-5 metres. [chart](https://pp.userapi.com/c848624/v848624077/50ee/-YJGOF8H5gY.jpg)
homey 1.5.11
app version v2.0.2
firmware version 3.1.8 and 2.7.0

**Comment by koktaildotcom** [comment]
Looks like there is a problem with the Bluetooth connection. Do you use other devices with the BLE on homey? Or do you use the Mi Flora App on your smartphone?

**Comment by daniel3** [comment]
Does it causes issues when you use the Mi Flora App in combination with the Homey app?

**Comment by koktaildotcom** [comment]
If the app is connected with BLE to the sensor the app cannot connect to the sensor.
