### ISSUE TITLE
Updating Sensors don´t work

### ISSUE THREAD

**Issue by m-holler** [koktaildotcom/homey-mi-flora#36]
I have 7 Xiaomi Sensors, and if i install the app new, and registering the 7 Sensors, the App will be work for About 1 day.
In the Settings you can choose the intervall of updating the sensors. I have set this value to 60 Minutes for now, but it won´t update the sensor data.
If i Restart the app, Nothing apears.
If i restard Homey, 1 or 2 Sensors have new data, the rest not.
How did you pull the sensor data ??? All at one time ??? What happend, when you can´t connect to one of These sensors ??? Will you try the other sensors, or will the app stop ???
In my opinion 2 new values in the General Settings make sense.

Number of retrays if something went wrong.

Delay between the poll from sensor to sensor. (If i have a pollingvalue of Default 15 minutes, then the second value can be 30 seconds, that means a delay before the second,third…. sensor datas are requested)

I have some other Bluetooth LE devices (Mipow), and there was a solution, to put a delay between the pull of the devices, if you have more than one.

Best regards, and thank you for coding such a nice app. :-)

**Comment by koktaildotcom** [comment]
The app updates the sensor's values one by one. If the sensor is unreachable or doesn't give a reponse the app will try it again up to three times. After that it wil move to the next. If all the sensors are updated or tried for 3 times the (configurable) delay wil be triggered. After that the whole process wil start again.

What is the firmware of the sensor?
What is the firmware of Homey?
Have you connected another device to the sensor? (Phone app xiaomi flora)
What is the distance from the sensor to Homey?

**Comment by m-holler** [comment]
Sorry for being late,
Firmware of Sensors: 3.1.8 and Pot 1.1.4
Homey: 1.5.11
Yes i have connect one IPhone, but if i am Ready with updating the sensorsdata, i will close the app, no Background Tasks.
The distance is 5 to max 8 meters.
Yes, i send now a report.
Hope it helps.

**Comment by m-holler** [comment]
The log ID=11A6122B2C

**Comment by koktaildotcom** [comment]
Firmware should be compatibel. Is bluetooth always enabled on your phone? Because that can cause a problem. (Sensor can only connect to one device)

5 - 8 meters

**Comment by koktaildotcom** [comment]
@m-holler can you send the log again? In `/manager/settings/#homey:manager:apps` hover the app: `homey-mi-flora` with the <alt> key and wait until the `Send to developer` button appear and click on it.

**Comment by m-holler** [comment]
@koktaildotcom: I am not able to send you the log, if i hover over the homey-mi-flora app Nothing apears. There is Nothing to enter the key. I have tryed it with Edge and Firefox 60. Mhhh strange Thing.

About your Questions above:
I have not tryed a Closer range, Bluetooth is Always on, on my mobile device, but the flora app is closed. 
I have tryed it with complete power off my mobile phone, and this makes no different.

**Comment by koktaildotcom** [comment]
Try `Google Chrome`.
Goto: /manager/settings/#homey:manager:apps
Click one time inside the white `frame` with: Apps installed on Homey
Hover the app: homey-mi-flora with the key and wait until the Send to developer button appear and click on it.

Can you try a closer range and check if the problem disappear?
Here the app is running for 4 months without any problems.

Do you have another app installed that uses BLE? Like a sound system or so?

**Comment by m-holler** [comment]
Ok, i have tried Google Chrome, but the Problem, no window or someting else Pops up, to sende the log to you. I think the Problem is, wich key i should use, and have i just copy and paste it ??? (i think this is a totaly noob Question :-) )
I have one other BLE-App installed on Homey, Mipow Playbulb (Experimental) from the homey devs.
Do you have recived Problem like mine from other users ????
Ps: I have homey logger installed, but if i choose your app, the logger means, this app supports no live loging….so this way is also not functional, to send you a logfile. :-(

Have a nice Weekend.

**Comment by koktaildotcom** [comment]
@m-holler any success in connecting the devices?

**Comment by Sagittarius-dk** [comment]
Hi koktaildotcom

Seems like i have the same problem, when I install the program and add the two sensors I have so far, it works fine, but now they stop updating...

**Comment by koktaildotcom** [comment]
@Sagittarius-dk 
What is the firmware of the sensor?
What is the firmware of Homey?
Have you connected another device to the sensor? (Phone app xiaomi flora)
What is the distance from the sensor to Homey?

Can you send a report to the developer in Homey app overview? (Hover with the **alt** key)

**Comment by Sagittarius-dk** [comment]
Firmware of the sensor are: v3.1.9
Homey Firmware Version: 1.5.11
Nope closed the program on my Iphone

The log has been sent to the developer.
The unique log ID is: d2ba6ff7-43fc-4772-a10a-d4d41a75f3fb

😊

**Comment by Sagittarius-dk** [comment]
Not sure what: Did you try a PTP to reset the Homey core? is ;/

Hmmm my problem is that its for Xiao1 the Soil moisture is really 18 and for Xiao2 its 33

I try restart the app now..

**Comment by koktaildotcom** [comment]
PTP = Pull the plug reboot Homey with a hard reset.

Can you verify that (look in insights) that the sensor isn't updated. Or are the value's not correct?

**Comment by Sagittarius-dk** [comment]
The values are not correct, let my try pull the plug on the Homey 😉

From looking at "Insights" seems like it gets some kind of information, but the values are wrong, from what I see in the app: "Flower Care"

![chart](https://user-images.githubusercontent.com/43027081/45145847-ebf05200-b1c1-11e8-8cf3-117cde37c8f4.jpeg)

**Comment by Sagittarius-dk** [comment]
after restart seem like Xiao1 made a huge jump down

![chart](https://user-images.githubusercontent.com/43027081/45148876-8c497500-b1c8-11e8-9c9f-98fb54a9bc65.jpeg)

**Comment by koktaildotcom** [comment]
What are the values in Homey and the mi flora app?

**Comment by Sagittarius-dk** [comment]
To day I think in the mi flora app it was 23 and homey was think like 34  
But not sure, I restarted homey and it made a new update

**Comment by koktaildotcom** [comment]
@Sagittarius-dk can you verify the differences in realtime after an update?

**Comment by Sagittarius-dk** [comment]
@koktaildotcom 
If you look at the screenshot, you can se the drop after restart. Is that what you are asking for?
And yes I look at the number in device first, before restart... even have an api, that Homey is sending the numbers to Fibaro HC2

<img width="2025" alt="screen shot 2018-09-10 at 09 03 28" src="https://user-images.githubusercontent.com/43027081/45281756-10f20700-b4d9-11e8-968a-7aec73818405.png">

<img width="773" alt="screen shot 2018-09-10 at 09 07 05" src="https://user-images.githubusercontent.com/43027081/45281757-14858e00-b4d9-11e8-8960-ff045b5b9c08.png">

**Comment by koktaildotcom** [comment]
The drop is caused because the sensor is updated again after a period of dis-connectivity. The Fibaro HC2 connection to Homey is unknown to me, can you provide a screenshot of the sensor in Homey and in the Mi flora app? The sensor is already updated to the latest firmware i suppose?

**Comment by koktaildotcom** [comment]
Looks like the values are corresponding the same except for `light intensity`. This however is a very fluctuate sensor and likely to change very often. The sensor in Homey is updated on interval, so its possible that the `live` value is changed already.

**Comment by Sagittarius-dk** [comment]
@koktaildotcom 

Jep Light Intensity goes fast up and down, but the most important is the moisture and fertilizer 😊

And thats seems to stop showing the correct numbers after a day or so...

**Comment by koktaildotcom** [comment]
That issue i cannot reproduce, you can try to add a flow in Homey like:
![image](https://user-images.githubusercontent.com/10741929/45291127-971a4780-b4f1-11e8-9838-28766cfcb82f.png)
That way you get a notice when Homey is not firing the next update event (on interval).

**Comment by Sagittarius-dk** [comment]
Sure 😊

**Comment by Sagittarius-dk** [comment]
@koktaildotcom 

Where do I find the “ADD to the log”

**Comment by koktaildotcom** [comment]
You need an app for that called: logger. Or you send a notification to your mobile.

**Comment by Sagittarius-dk** [comment]
I did setup the push notification... and the zone in my system are also called MiFlora?

**Comment by koktaildotcom** [comment]
I don't think so. You can filter in the 'and' column on a specific zone or do a match on a name.

You can test this by logging the zone and name of now. Then you can specify a filter

**Comment by Sagittarius-dk** [comment]
Think I found out, moved my sensors Xioa1 and Xioa2 to the garden zone and made the flow with that name 😊

**Comment by Sagittarius-dk** [comment]
@koktaildotcom

Its working fine so far, just to let you know 😊

<img width="1979" alt="screen shot 2018-09-11 at 13 26 35" src="https://user-images.githubusercontent.com/43027081/45357461-97384700-b5c6-11e8-967c-6c496bb62e6a.png">

**Comment by koktaildotcom** [comment]
Good to hear! Thanks for your message :)

**Comment by Sagittarius-dk** [comment]
@koktaildotcom 
HI
it stoped working, have send you a log

<img width="2011" alt="screen shot 2018-09-15 at 14 02 00" src="https://user-images.githubusercontent.com/43027081/45586053-53a84a80-b8f0-11e8-8480-671b3796f80e.png">
