### ISSUE TITLE
Trigger card: close to treshhold

### ISSUE THREAD

**Issue by cbho** [koktaildotcom/homey-mi-flora#44]
Hi,
was wondering if it would be possible to add another trigger card with something like "Sensor value within X of configured threshold" - that is, within the configured interval, but closing in on the limit...

That would allow for setting the limits for moisture etc. for each sensor corresponding to the plant and be able to make not only a flow triggered by the moisure (e.g.) being outside the limits, but also to make flows that trigger when you are getting close - that is, make it possible to react in due time instead of (kind of) too late...

Of course, flows can be made that correspond to a specific sensor - but a card using or more generic approach would allow for fewer flows :-)

**Comment by koktaildotcom** [comment]
Nice idea, that wil be a nice improvement. Is narrowing the threshold not an option in this case? If your plant will die with moisture level of 40% you should make the max 20% for example.

I'm currenty working on a 'status report' that can be sent to email. That wil give you better insights of your plants will survive. 

![screenshot_20180918-220542](https://user-images.githubusercontent.com/10741929/45713373-2f1dce00-bb8f-11e8-98d7-c4c7833e3f1f.png)

**Comment by cbho** [comment]
Sure, narrowing the threshold is the "straight-on" approach - and that's what I do now - but still, it's kind of a work-around ;-)
I use the Slack-app (with an totally my-eyes-only-channel) for battery alerts, non-reporting devices - and flowers - then I don't have to incorporate a "mute" time interval in my flows - and then just mute the Slack channel automatically during the night...
(And when my son is at home, messages are directed to him so that he can get on watering the flowers, but if he's not, I'll get them and the flowers will survive)...

Adding this option would make it possible to make a flow that goes "consider watering your flowers somewhere in the future" that use whatever standard channel to inform you about it when you get home, when you get up, whatever - and than also have some hard limits for a flow saying "water this plant or loose it" :-)

Getting e-mail reports is one way - not sure I would fancy that, but a nice feature - and I'm totally aware that this is absolutely in the "nice to have" area and not getting it woudln't raise a single eyebrow here...

Regarding the limit:
Not sure wether an absolute or a relative limit would be best - think it's just as much a matter of what would be easy to implement :-)
Either way, I think it should be a value that could be entered by the user, not a flow card with a fixed value...
Thinking in generic flow card terms, a card with relative values might be the best - perhaps a card that uses the average of the minimum and maximum value allowing you to set "if value differ more than xx% from baseline" given that average is baseline and 100% is the limits (don't apply statistical thinking, normal variation, and stuff like that on this - and definitely not botanical knowledge - only a matter of getting some kind of stratified alarms...)

**Comment by koktaildotcom** [comment]
I think this solution isn't that strait forward. I suggest you should make the threshold bigger.
