### ISSUE TITLE
No Data from sensor

### ISSUE THREAD

**Issue by hplos** [koktaildotcom/homey-mi-flora#52]
I'm getting no data from my sensor. In the app everything is working fine.

**Comment by koktaildotcom** [comment]
What is the firmware of the sensor?
What is the firmware of Homey?
Have you connected another device to the sensor? (Phone app xiaomi flora)
What is the distance from the sensor to Homey?

Can you send a report to the developer in Homey app overview? (Hover with <alt> key pressed)

**Comment by mhoogenbosch** [comment]
Got the same issue. Firmware of homey is latest in beta channel (1.5.13-rc.11) and just updated the device to the latest firmware 3.17. Only thing is my device is from FlowerCare. Ordered it through AliExpress and don't know if it is the right one.

**Comment by hplos** [comment]
I think the problem is solved.
The sensor must not be coppled with my phone for de mi flora app, so I checked my bluetooth settings in my phone, and there was no flora sensor. 

Apparently I had to remove the sensor from de flora app. After that I added the sensor again and now I’m getting data from the sensor.

Thnx!

**Comment by koktaildotcom** [comment]
Good to hear that you resolved the issue.
