### ISSUE TITLE
Other Xiaomi BLE devices

### ISSUE THREAD

**Issue by WinSCaP** [koktaildotcom/homey-mi-flora#60]
Hi koktaildotcom,

Are you planning to add other Xiaomi BLE devices to your code. Specifically this one: https://www.aliexpress.com/item/Original-Xiaomi-Mijia-Smart-Indoor-Temperature-Humidity-Monitor-Bluetooth-mi-Home-App-Control-Air-Conditioning-Fan/32845378033.html

Kind regards,
WinSCaP

**Comment by koktaildotcom** [comment]
You can make an app request for Homey: https://community.athom.com/t/homey-community-app-requests/2713
