### ISSUE TITLE
App needs additional permission on v.2.0.0

### ISSUE THREAD

**Issue by mhoogenbosch** [koktaildotcom/homey-mi-flora#61]
After upgrading from 1.5.13 to 2.0.0.rc it looked like everything was workig fine, untill today i didn't notice anything was wrong. But I havent received a message for a while now so I looked at the status. The status was refreshed 9 days ago. 

After removing and trying to add the sensor i get the following message:
Cannot get devices:Cannot discover BLE devices from the homey manager. Error: missing_permission:homey:wireless:ble

I recongize this error because BLE Christmas Lights had the same problem. He had to create a new app with permissions specifically set voor v2 firmware.

**Comment by koktaildotcom** [comment]
I've already tried to add the permissions the day 2.0 came out. But the Homey gives a lot of other issues on 2.0. 

I've already submitted 3 BLE issues to GH. I'm working hard on this, but at the moment it is broken.

**Comment by koktaildotcom** [comment]
Thanks for testing it!

**Comment by mhoogenbosch** [comment]
There seems to be a bit of a problem with the app. If I reboot the Homey after the app has been installed it breaks. I cannot reach it anymore. After removing the app during the boot process of the apps i can manage to reach the homey. 

Is there a way I can help you with testing?

**Comment by mhoogenbosch** [comment]
You mentioned you are having some difficutlies with the BLE implementation of Homey. Another dev'er I've been talking to (to get my BLE christimas lights running) was complaining about the BLE as well. Maybe, if you are running into some issues you could contact him? https://github.com/gruijter/com.gruijter.clusterlights/tree/15d498a119e162486d4e377b11b2b87b543607d3 Don't know if you are willing to do so but, he managed to find a way to get stuff working correctly.
