### ISSUE TITLE
HomeyKit stops working

### ISSUE THREAD

**Issue by realmnm** [koktaildotcom/homey-mi-flora#62]
When I enable the "Xiaomi Mi Flora" app on my Homey my "HomeyKit" app stops working. I can see when sensors are triggered in HomeKit, but I can´t turn on/off lights for instance. As soon as I Disable the "Xiaomi Mi Flora" app the Homekit integration starts to work again. I use 1.5.13 on my Homey and 2.0.18 on the Xiaomi Mi Flora App.

**Comment by koktaildotcom** [comment]
I don't know the HomeyKit app and the compatibilty with flora app. Can you enable the app and send a log to the developer?

**Comment by koktaildotcom** [comment]
Try Google Chrome.
Goto: /manager/settings/#homey:manager:apps
Click one time inside the white frame with: Apps installed on Homey
Hover the app: homey-mi-flora with the "alt" key and wait until the Send to developer button appear and click on it.

**Comment by realmnm** [comment]
I have now enabled the app and send the log.
