### ISSUE TITLE
Can't add sensors (permission problem?)

### ISSUE THREAD

**Issue by Purifier2** [koktaildotcom/homey-mi-flora#64]
When trying to add a sensor it returns a message: 

"Cannot get devices:Cannot discover BLE devices from the Homey manager. Error: missing_permission:Homey:wireless:ble"

**Comment by Purifier2** [comment]
I'd like to try the alpha version. it's better than nothing

**Comment by koktaildotcom** [comment]
> I'd like to try the alpha version. it's better than nothing
PM me your emailaddress from your Homey, i'll add you to the list!
