### ISSUE TITLE
Missing permission: homey:wireless:ble

### ISSUE THREAD

**Issue by Allfredos** [koktaildotcom/homey-mi-flora#65]
I update my homey to 2.0 today and my flora sensor have stopt working. I removed the sensor and tried to add it but i got error. Tried reintall but it faild again
The error code is:
Error: missing_permission:homey:wireless:ble

**Comment by koktaildotcom** [comment]
The app is not compatible with 2.0 because of a Homey BLE core issue's

**Comment by Allfredos** [comment]
Oh, thought it was just for the rc in homey. I hope they will fix it soon. Tnx for the info.

**Comment by koktaildotcom** [comment]
Ahtom wil resolve that issue in v2.x they said. You'r welcome, happy to help. I will reopen the issue again because there wil be more people with the same question i assume.

**Comment by koktaildotcom** [comment]
See: https://github.com/athombv/homey-apps-sdk-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ble
