### ISSUE TITLE
Doesn't seem to update

### ISSUE THREAD

**Issue by sg-jorrit** [koktaildotcom/homey-mi-flora#67]
Hi koktaildotcom,

There seems to be a problem with the app. It doesn't update the values once it's started. I have to restart the app in order to make it fetch new readings. It will read the sensors once, then just stops updating.

Once you restart the app every 15 minutes (currently done with the new System experiment Flow card action to restart the app), it seems to work more or less (have this in place as of 14:00). But that really shouldn't have to be done to make it update.

The refresh setting does not fix anything. Tried values of 10 minutes, 15 minutes and 30 minutes. All would not update any sensor data after first fetch.

Installed latest beta version of app (2.1.0) and latest Homey rc (2.0.5.rc2).

![screenshot 2019-03-05 at 16 33 22](https://user-images.githubusercontent.com/733419/53816761-709b0d80-3f64-11e9-9210-8ca263023e6f.png)

Edit: just noticed this notice;
```
The app is rewrited for v2.0 but does update just once due to Homey core issues as mentioned in de skd-app issue ticket to athom on github. Athom is looking for a fix for this issue ‘soon’ untill than the app wil not be fully compatibel with v2.0.
```
Well, that seems to answer it. At least the workaround seems to work for now. I'll just await Athom's fix patiently. :-)

**Comment by koktaildotcom** [comment]
Thanks for submitting the issue. I'm currently working on  this issue and will be resolved very zoon.
