### ISSUE TITLE
Polling interval not working

### ISSUE THREAD

**Issue by Ziglar1** [koktaildotcom/homey-mi-flora#68]
since 2 months or so, the polling interval does not work. 
it does not matter if i let the interval on default or set it to a specific time, it does not refresh.
once i restart the app, the information is collected.
any ideas on what i might be doing wrong, or could this be fixed ?

kind regards, 
Ziglar

**Comment by koktaildotcom** [comment]
Hey Ziglar.

The issue is not the pollinginterval but a Homey core issue conserning the BLE manager.

https://github.com/athombv/homey-apps-sdk-issues/issues/73
