### ISSUE TITLE
Identify sensor with led blink

### ISSUE THREAD

**Issue by ghost** [koktaildotcom/homey-mi-flora#7]
I own 7 sensors and would like an option to identify the sensor (led blink)

Any way to implement this?

**Comment by koktaildotcom** [comment]
I't should be a nice feature. On connecting to the BLE the sensor does a blink with its led. I can't find a specific `ble characteristic` that implement this directly however.

**Comment by StraDijk** [comment]
In the Android Xiaomi app there is an option to let the led blink.

**Comment by koktaildotcom** [comment]
I've seen it. But the xiaomi sensor is closed source. And i cannot find any documentation about it online.

**Comment by koktaildotcom** [comment]
@ghost this issue is resolved in v2.1.4 and is currently in review for beta
