### ISSUE TITLE
Trigger "sensor below value" releases even if value is above high value.

### ISSUE THREAD

**Issue by betonmoewe** [koktaildotcom/homey-mi-flora#71]
Trigger for plant X: "Sensor value is below the configured threshold" + "The plant has not enough moisture" -> Alarm
results even in an alarm if moisture is above threshold: low = 20, high = 80 ... after watering the plant, the moisture value was above 80 and the alarm was released every time, the sensor was refreshed. After some hours the value droped below 80 and no alarm was send any more.

**Comment by koktaildotcom** [comment]
Are you sure you don't use the trigger card: `Sensor value is outside the configured threshold`?

What version you use of the app?
What version you use of Homey?

**Comment by betonmoewe** [comment]
I have used „the plant has not enough moisure“ just double-checked 
version of your app: 2.6.1
version oh homey: 2.1.1

Best regards 

Betonmoewe

**Comment by koktaildotcom** [comment]
I've have reproduced the issue, i'll look into it.

**Comment by koktaildotcom** [comment]
There is no condition card `sensor below value`. The description of the condition cards are wrong. There are only condition cards to verify that the sensor within the threshold of the sensor.

`The plant !{{has not|has}} enough moisture.` should be `The plant !{{has not|has}} correct amount of moisture.`

I've fixed that in release v2.1.7

For your flow you can use an `logic` condition for now.

Add a new `condition` card:
1. Logic
2. [TAG] is lower than
3. [TAG] select [Device -> Moisture]
4. Duplicate the threshold value you want to check
