### ISSUE TITLE
Add `condition card` below and above threshold.

### ISSUE THREAD

**Issue by koktaildotcom** [koktaildotcom/homey-mi-flora#73]
As a result of @betonmoewe issue: https://github.com/koktaildotcom/homey-mi-flora/issues/71

Add 2 new cards for determining if a value is below or above its threshold.

**Comment by betonmoewe** [comment]
Thanks for your fast fix !
How long does it take until I have this new version?

Best regards 

Betonmoewe

Von meinem iPad gesendet

**Comment by koktaildotcom** [comment]
I don't have the time right now to look into this. I'll keep the issue open until its fixed.
