### ISSUE TITLE
Data is not updated regularly from the sensor

### ISSUE THREAD

**Issue by gizmodok** [koktaildotcom/homey-mi-flora#75]
Hi,

I have a Xiaomi minflora ( Chinese edition)a few days.
At the beginning there where no problems it was updated regularly but now the updates intervals are like 8 or 9 hours.

I’ve tryide to change the setting no effect,
I’ve rebooted the sensor no effect,
I’ve changed the settings because I thought there was an issue with the range no problem every change is saved without time out.

Homey firmware is: 2.1.2
App ver: 2.1.10
Mi Flora firmware: 3.2.1
Log id: f98be123-522c-48da-b42c-d46c9c988c82

I hope you can see what’s wrong 

Kind regards,
Kamil Kuchta

**Comment by gizmodok** [comment]
I’ve rebooted homey and the app but still no update for more than 2 days.  Please see log 0312677d-e952-4be2-8112-5d8da801c3fc

**Comment by koktaildotcom** [comment]
The 'find' function on the object gives an error: 'could_not_find_peripheral'. What version of BLE device do you use? Flora pot or Sensor? And what is your firmware version?

**Comment by gizmodok** [comment]
Hi I’m using sensor

App ver: 2.1.10
Mi Flora firmware: 3.2.1

**Comment by gizmodok** [comment]
Please see screenshot en log a few minutes ago where some things updated but not everything see screenshot and log 3d2cafd3-c3e7-4f80-a90c-7197f38be3ac
![4B664778-8764-4EE3-BDB0-E76BB46B83DD](https://user-images.githubusercontent.com/23284970/58573196-86576080-823d-11e9-9204-672a3d3bd5a3.png)

**Comment by koktaildotcom** [comment]
That is because the value is not changed. That is homey logica. ;)
