### ISSUE TITLE
Sensors not working after few hours 

### ISSUE THREAD

**Issue by tom9865** [koktaildotcom/homey-mi-flora#77]
Hi, great app! Worked like a charm!
But after only few hours sensors both stop working. No update anymore. Last update of both sensors is 2 days ago. 

Anything to do with setting of treshold values?

Treshold values set manually, poll interval 30min. Furthermore I am restarting the app every night via homey flow. 

Homey firmware is: 2.1.2
App ver: 2.1.10
Mi Flora firmware: 3.2.1

Issue report
3353ab2f-a193-4955-a999-ce1d132df65f

Any idea how to get and keep this working?!

**Comment by koktaildotcom** [comment]
Try to update to the latest version of the app. This revolves the issue.

**Comment by tom9865** [comment]
Hi, thanks for the reply! I tried updating several times. Seems that I already have the latest Version of the app installed.
Issue remains. After a few Hours the sensors are not reporting anymore ☹

Any other idea? Any Chance to analyze some logfiles or anything?

br / bg,
Tom

tom@hillen.me
+49 1577 8305057

**Comment by koktaildotcom** [comment]
Please send a log, but i think there are some conditions that interfere with Homey's BLE or something.

**Comment by tom9865** [comment]
Thanks for the info.
Report created. Unique Code: 328c9bb8-5781-4817-b324-6898b78e7407

br / bg,
Tom

tom@hillen.me
+49 1577 8305057

**Comment by koktaildotcom** [comment]
I've looked to the log. You like your veggies! ;) But no specific error occur. Only that the sensor sometimes get an timeout because of the distance. Rebooting Homey may resolve the issue for a while, but i cannot do anything more. Did you replace the adapter of the Homey already?

**Comment by tom9865** [comment]
I love my veggies... ??
Thanks for the great implementation!!!

Ok. Understood.

Where can I find an instruction how to replace / upgrade the Adapter of homey?
Do I understand you correctly? – There is a BT LE mod that ensures better Signal Quality / Extended reach?

I have a Restart scheduled for homey once a day. Furthermore the app Mi Flora is restarted everyday at lunch time too...

br / bg,
Tom

tom@hillen.me
+49 1577 8305057

**Comment by koktaildotcom** [comment]
> I love my veggies... ?? Thanks for the great implementation!!! Ok. Understood. Where can I find an instruction how to replace / upgrade the Adapter of homey? Do I understand you correctly? – There is a BT LE mod that ensures better Signal Quality / Extended reach? I have a Restart scheduled for homey once a day. Furthermore the app Mi Flora is restarted everyday at lunch time too...

Vegetables.. ;)

You can try a 2A adapter to connect power to Homey, the one provided in the first batches are not that great. Not that this will fix the issue, but you can try.

After a restart all the devices are synced correctly? Can it be that after a connection timeout (BLE is out of range) the device is `frozen` and not updated anymore?

Can you move the sensors within a range of 5 meters and reboot Homey. If that doesn't result in the same behavior the above scenario is true.

**Comment by tom9865** [comment]
Thanks!
I love my veggies indeed I meant ??
So no ??, !! instead ??

So understood correctly?


  1.  I should try to add another (3rd Party) 2A power connector (the usb power connector) – implying that the power connector does not give homey enough power?
  2.  Move homey in 5m range of all sensors, reboot and check again if that’s helping?

Till now a Restart Always helps to sync nearly all devices...

br / bg,
Tom

tom@hillen.me
+49 1577 8305057

**Comment by koktaildotcom** [comment]
I understand now! :) If you can try that it will verify the issue.

**Comment by koktaildotcom** [comment]
Any luck with the changes?
