### ISSUE TITLE
Homey doesn't find Mi Flora sensor

### ISSUE THREAD

**Issue by Bartm4** [koktaildotcom/homey-mi-flora#78]
The sensor is not found by the Homey app. 
- It is found by the app from mi flora itself
- I have removed it from the app after i checked if the firmware was up to date.
- I have it next to the Homey (within 10cm) when trying to connect

What else can i try?

**Comment by Ziglar1** [comment]
same here

**Comment by koktaildotcom** [comment]
I'm sorry for not responding quickly. I'm currenty very bussy. Can you send a log, then i'll take a look.

**Comment by Ziglar1** [comment]
there is no where to make a log.
please check the video : https://dejong.pro/flora.mp4

**Comment by Ziglar1** [comment]
any idea @koktaildotcom  ?

**Comment by koktaildotcom** [comment]
Apps -> Xiaomi flora -> Settings (cogwheel icon) -> Diagnostic report

**Comment by Ziglar1** [comment]
f1a7d3c8-ea9c-4075-ab27-8498812d51f8

**Comment by koktaildotcom** [comment]
Looks like your ble module don't respond.

**Comment by koktaildotcom** [comment]
works fine on:

Homey @ 2.4.1
Homey Pro @ 2.4.0

With latest version of the app: 2.1.10

**Comment by Bartm4** [comment]
Works! Perfect thanks for the effort
