### ISSUE TITLE
Naming of variables

### ISSUE THREAD

**Issue by cbho** [koktaildotcom/homey-mi-flora#8]
The used nomenclature for variables in the app include that the measured values are named with the prefix "measure_" - this means, that if the token "sensor" is used to compose a log message like shown in the example below, text will be "[Device name]: **measure_moisture** is too low ([value])".

![ex-1](https://user-images.githubusercontent.com/29979509/38642809-813e8850-3ddb-11e8-97b5-38b41380642f.JPG)

Although the logic in naming the variable is obvious and has many advantages, I suggest the variables for the measured values are names _without_ the prefix (only "moisture", e.g.) in order to make composed messages more "clean" and ordinary language-like.
This would also prevent the situation that a message read out would like "[Device name]: **measure-underscore-moisture** is too low ([value] :-)

**Comment by koktaildotcom** [comment]
The sensor is now the id of the `capability`, it should indeed get the name of the `capability` in the users preferred language.

**Comment by koktaildotcom** [comment]
The tag `sensor` will now contain the `capability` in the users preferred language.
