### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by JackDaniel007** [koktaildotcom/homey-mi-flora#80]
Enclosed the files of the translation

[de.json.zip](https://github.com/koktaildotcom/homey-mi-flora/files/3529592/de.json.zip)
[app.json.zip](https://github.com/koktaildotcom/homey-mi-flora/files/3529595/app.json.zip)

**Comment by koktaildotcom** [comment]
Thanks for your contribution!

**Comment by koktaildotcom** [comment]
I've added the translations and your name to the translators to the repository. It is currently in review. If you want your name and email please send it to me in a PM.

**Comment by JackDaniel007** [comment]
no thanks is not necessary ;)
