### ISSUE TITLE
Threshold update Unknown_Error

### ISSUE THREAD

**Issue by sHiKoRa** [koktaildotcom/homey-mi-flora#83]
Great app, thank you for that. When adding (min or max) thresholds values in advanced settings an error occurs when submitting it to the device. "An unknown error has occured [unkown error]". Firmware version 3.2.1 / Diagnostic rapport: 6346f9f6-e6a5-41ec-bfbd-230be23248ed.

**Comment by koktaildotcom** [comment]
Thanks for reporting an issue. I cannot reproduce the issue you having. 

In the log i see:

```
{ Error: Cannot read property 'startHandle' of undefined
    at Remote IPC Process

  message: 'Cannot read property \'startHandle\' of undefined' }

```

I think that is device specific because there is no such thing in the app.

**Comment by sHiKoRa** [comment]
Hi koktaildotcom, thanks for you quick response. Yes I can edit any other device (about 35), but these are only Z-Wave or Zigbee devices. However the Xiaomi Mi Flora is the only Bluetooth device.

**Comment by koktaildotcom** [comment]
Can you edit the settings of other xiaomi flora devices?

**Comment by sHiKoRa** [comment]
Sorry for the late response koktaildotcom. Unfortantley this is my first Xiaomi Flora to see how it works (with Homey).

**Comment by koktaildotcom** [comment]
You can try removing and adding it again. Its an Homey core error that is thrown and not from within the app.
