### ISSUE TITLE
Connection issue after moving flora device out of reach (I think)

### ISSUE THREAD

**Issue by EmielCapelle** [koktaildotcom/homey-mi-flora#84]
Have an issue with the MI flora device. Worked for quite some time and was providing steady data. I had to relocate one plant because we're preparing for a move to another house. I think the MI flora was out of reach for a bit too long. Haven't been able to read new values ever since. Please help. 
dc6756a3-fc0e-420e-a95f-e426f3119453

**Comment by koktaildotcom** [comment]
Looks like your device isn't excess-able anymore. Can you connect with it with the Xiaomi mi flora app?
