### ISSUE TITLE
No data received with sensor mi-flora v2.3.0

### ISSUE THREAD

**Issue by dbuekenh** [koktaildotcom/homey-mi-flora#88]
I am using version 2.1.13 from the homey xiaomi mi flora.

I have 2 sensors hhcc from xiaomi. Both are working fine in the app vegtrug grow care. I updated both to the latest version which is 2.3.0.

![image](https://user-images.githubusercontent.com/47578509/89728366-278a9b00-da2d-11ea-95c9-c98a96ca130d.png)

When adding both sensors to homey they are found. And displayed in the devices tab of homey app. 

When selecting one no data is shown. The orher one has the same issue.

![image](https://user-images.githubusercontent.com/47578509/89728420-88b26e80-da2d-11ea-9edd-90354698c210.png)

![image](https://user-images.githubusercontent.com/47578509/89728426-9536c700-da2d-11ea-8074-9890c4c20170.png)

![image](https://user-images.githubusercontent.com/47578509/89728432-9f58c580-da2d-11ea-9ada-4dbdc7a62cce.png)

I have made a homey diagnostic report 0e371201-6da3-4148-a63d-2c6c7def2775.

With older software versions of the sensors data was shown bit never updated.

Let me know if you need some more information.

Rgds dirk

**Comment by dbuekenh** [comment]
Anyone?

**Comment by shaarkys** [comment]
So far it seems it's Homey bug

**Comment by koktaildotcom** [comment]
Its because: https://github.com/athombv/homey-apps-sdk-issues/issues/117
