### ISSUE TITLE
Miflora Bluetooth not found in Node Red...

### ISSUE THREAD

**Issue by uniklnurulain95** [koktaildotcom/homey-mi-flora#89]
![Ble](https://user-images.githubusercontent.com/44824934/91681063-cebba780-eb7f-11ea-93a5-259751d44cd0.PNG)

Anyone know why...?

**Comment by koktaildotcom** [comment]
This is the repository for the Homey app. I don't know what you are using.

Can you provide a proper bugreport.
I miss:

    Expected vs. actual results
    Steps to reproduce
    Environment

**Comment by uniklnurulain95** [comment]
> 
> 
> This is the repository for the Homey app. I don't know what you are using.
> 
> Can you provide a proper bugreport.
> I miss:
> 
> ```
> Expected vs. actual results
> Steps to reproduce
> Environment
> ```

I'm using:
Hardware : Raspberry Pi
Sensor : Miflora
IoT platform :  Node-red

I'm really sorry ya, wrong repository...sorry sorry...
