### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by MrXCuci** [koktaildotcom/homey-mi-flora#90]
Works with the flower care app, but not with Homey. I removed the device from the flower care app, but still no device found. Device hardware firmware 3.2.2 type HHCCJCY01HHCC cmit Id: 2016DP0940 Hope we can fix this. Homey Pro device.

**Comment by MrXCuci** [comment]
1a6646d4-8a16-4a14-bbd0-358da0178d55

**Comment by koktaildotcom** [comment]
Its because: athombv/homey-apps-sdk-issues#117

**Comment by MrXCuci** [comment]
After several attempts it worked.
